name: Test
on: [push]

jobs:

  test:
    name: Test on push
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get test dependencies
      id: get-test-deps
      run: |
        go get -v -t ./...
        go get -v -t -u golang.org/x/lint/golint \
        	honnef.co/go/tools/cmd/staticcheck \
          github.com/golangci/golangci-lint/cmd/golangci-lint \
        	github.com/fzipp/gocyclo

    - name: go test
      run: go test ./cmd/gocate

    - name: gocyclo
      run: gocyclo ./cmd/gocate

    - name: golangci-lint
      run: golangci-lint run ./cmd/gocate
