---
name: Test
"on": [push]
permissions: read-all
jobs:
  test:
    name: Test on push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v8.0.0
      - name: Get test dependencies
        run: |
          go mod download
      - name: go test
        run: go test ./cmd/gocate
