name: Test
on: [push]

jobs:

  test:
    name: Test on push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - uses: golangci/golangci-lint-action@v2
    - name: Get test dependencies
      run: |
        go mod download
    - name: go test
      run: go test ./cmd/gocate
